### PR TITLE
IOS multi page problem fixed

### PR DESCRIPTION
**Pull request by raifozdogan**

### CODE REVIEW

**Comment by liumengchun** [comment]
Just tested, the problem of multiple IOS pages still exists (blank pages with more IOS)

**Comment by raifozdogan** [comment]
@liumengchun 
Hey Chun 

In my case, the content was not going to the second page. I don't know about the problem you're talking about. I'd like to help if you explain.

**Comment by liumengchun** [comment]
> @liumengchun 嘿春
> 
> 就我而言，内容不会进入第二页。我不知道你说的问题。如果你解释一下，我想帮忙。

After using your code, I didn't fix the extra blank pages in IOS

**Comment by liumengchun** [comment]
> @liumengchun 嘿春
> 
> 就我而言，内容不会进入第二页。我不知道你说的问题。如果你解释一下，我想帮忙。
After using your code, I fixed the redundant blank pages in IOS (I thought your code was submitted at first. Hahaha)

**Comment by raifozdogan** [comment]
@liumengchun So the blank page problem has been fixed? 🙃

**Comment by liumengchun** [comment]
> @liumengchun那么空白页问题已经解决了吗？🙃

OK, it has been solved. Thank you

**Pull request closed without merging**
